package com.sh.doorbell.registerandactivate.form;

import com.sh.base.form.BaseForm;
import com.sh.doorbell.registerandactivate.entity.EquipInfoEntity;

public class EquipInfoForm extends BaseForm<EquipInfoEntity> {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equip_info.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equip_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    private Integer type;

    private String data;

    private String area;

    private String typename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equip_info.user_id
     *
     * @return the value of equip_info.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equip_info.user_id
     *
     * @param userId the value for equip_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equip_info.status
     *
     * @return the value of equip_info.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equip_info.status
     *
     * @param status the value for equip_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }


    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getTypename() {
        return typename;
    }

    public void setTypename(String typename) {
        this.typename = typename;
    }

    @Override
    public void EntityToForm(EquipInfoEntity entity) throws Exception {
        super.EntityToForm(entity);
        if (entity.getEquipTypeEntity() != null){
            this.typename = entity.getEquipTypeEntity().getName();
        }
    }
}
