package com.sh.doorbell.devicecontrol.entity;

public class EquipTypeEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equip_type_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equip_type_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equip_type_info.id
     *
     * @return the value of equip_type_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equip_type_info.id
     *
     * @param id the value for equip_type_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equip_type_info.name
     *
     * @return the value of equip_type_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equip_type_info.name
     *
     * @param name the value for equip_type_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}