package com.sh.doorbell.registerandactivate.dao;

import com.sh.doorbell.registerandactivate.entity.EquipInfoEntity;
import org.springframework.stereotype.Repository;

import java.util.HashMap;
import java.util.List;

@Repository
public interface EquipInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_info
     *
     * @mbggenerated
     */
    int insert(EquipInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_info
     *
     * @mbggenerated
     */
    int insertSelective(EquipInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_info
     *
     * @mbggenerated
     */
    EquipInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EquipInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EquipInfoEntity record);

    List<EquipInfoEntity> selectAll();

    List<EquipInfoEntity> selectByMap(HashMap map);

    int selectCoutByMap(HashMap map);
}